# Change the code as it was generated by ChatGPT
import numpy as np

import utils

def generate_spike_train(rate, duration, refractory_period=0):
    """
    Generate spikes using a Poisson process.

    Parameters:
    rate (float): Firing rate in Hz.
    duration (float): Duration of spike train in seconds.
    refractory_period (float): Refractory period in seconds. Default is 0 (no refractory period).

    Returns:
    np.array: Times of spikes.
    """
    current_time = 0
    spike_times = []

    while current_time < duration:
        # If a refractory period is set and there was a previous spike, add the refractory period to the current time.
        if refractory_period > 0 and spike_times:
            current_time += refractory_period

        # Draw the next spike time from an exponential distribution
        next_spike = np.random.exponential(1 / rate)
        current_time += next_spike

        # Record the spike time if it's within the duration
        if current_time < duration:
            spike_times.append(current_time)

    return np.array(spike_times)

def question1():
    # Parameters
    firing_rate = 35  # Hz
    duration = 1000  # seconds
    window_sizes = [0.01, 0.05, 0.1]  # 10 ms, 50 ms, 100 ms

    # Generate spike trains
    spike_train_no_refractory = generate_spike_train(firing_rate, duration)
    spike_train_with_refractory = generate_spike_train(firing_rate, duration, 0.005)  # 5 ms refractory period

    # Calculate Fano factors and coefficients of variation
    fano_no_refractory = utils.calculate_fano_factor(spike_train_no_refractory, window_sizes, duration)
    fano_with_refractory = utils.calculate_fano_factor(spike_train_with_refractory, window_sizes, duration)
    cv_no_refractory = utils.calculate_coefficient_of_variation(spike_train_no_refractory)
    cv_with_refractory = utils.calculate_coefficient_of_variation(spike_train_with_refractory)

    # Display the results
    print("No Refractory Period:")
    print("Fano Factors:", fano_no_refractory)
    print("Coefficient of Variation (CV) of ISI:", cv_no_refractory)

    print("\nWith 5 ms Refractory Period:")
    print("Fano Factors:", fano_with_refractory)
    print("Coefficient of Variation (CV) of ISI:", cv_with_refractory)
